server:
  port: 8080

spring:
  datasource:
    username: yuan
    password: Yuan!123
    url: jdbc:mysql://192.168.56.9:3306/mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.mybatis.entity

logging:
  level:
    com:
      example:
        mapper: debug
